---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: bian-service-operations
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: io.example
  name: bian-service-operations
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bian-service-operations
